version: '3'
services:
  project:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
#    network_mode: host
    image: poc_project:latest
  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - database:db
    ports:
      - 8181:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root

